const PDFDocument = require('pdfkit');

const COLORS = {
  primary: '#4338ca',
  primaryLight: '#6366f1',
  text: '#1f2937',
  textLight: '#6b7280',
  border: '#e5e7eb',
  success: '#059669',
  successBg: '#ecfdf5',
  fail: '#dc2626',
  failBg: '#fef2f2',
  uncertainBg: '#fffbeb',
  uncertain: '#d97706',
  white: '#ffffff',
  placeholder: '#ea580c',
  consistency: '#2563eb',
  compliance: '#dc2626',
  formatting: '#9333ea',
  missing_data: '#059669',
  sectionBg: '#f9fafb',
};

const ERROR_TYPE_LABELS = {
  placeholder: 'Placeholder',
  consistency: 'Consistency',
  compliance: 'Compliance',
  formatting: 'Formatting',
  missing_data: 'Missing Data',
};

const SEVERITY_LABELS = {
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

const generateReportPdf = (report, user, team) => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `QC Analysis Report - ${report.filename}`,
      Author: user?.name || 'QC Checker',
      Subject: 'Quality Control Analysis Report',
    },
  });

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // --- Header ---
  doc
    .rect(0, 0, doc.page.width, 100)
    .fill(COLORS.primary);

  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor(COLORS.white)
    .text('QC Analysis Report', 50, 30, { width: pageWidth });

  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#c7d2fe')
    .text('Generated by QC Checker', 50, 58, { width: pageWidth });

  doc.moveDown(2);
  doc.y = 120;

  // --- Report Info Section ---
  drawSectionHeader(doc, 'Report Information', pageWidth);

  const analysedDate = report.analyzedAt
    ? new Date(report.analyzedAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    : 'N/A';
  const generatedDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  const infoRows = [
    ['Document Name', report.filename],
    ['Analysed By', user?.name || 'Unknown'],
    ['Email', user?.email || 'N/A'],
  ];

  if (team) {
    infoRows.push(['Team', team.name]);
    if (team.teamLead) {
      const leadName = typeof team.teamLead === 'object' ? team.teamLead.name : null;
      if (leadName) infoRows.push(['Team Leader', leadName]);
    }
  }

  infoRows.push(
    ['Analysis Date', analysedDate],
    ['Report Generated', generatedDate],
    ['Pages in Document', String(report.metadata?.pageCount || 'N/A')],
    ['Word Count', String(report.metadata?.wordCount || 'N/A')],
  );

  drawInfoTable(doc, infoRows, pageWidth);

  // --- Overall Result ---
  checkPageBreak(doc, 100);
  drawSectionHeader(doc, 'Overall Result', pageWidth);

  const label = report.qualityAssessment?.label;
  const resultText = label === 'good' ? 'PASSED' : label === 'bad' ? 'FAILED' : 'UNCERTAIN';
  const resultColor = label === 'good' ? COLORS.success : label === 'bad' ? COLORS.fail : COLORS.uncertain;
  const resultBg = label === 'good' ? COLORS.successBg : label === 'bad' ? COLORS.failBg : COLORS.uncertainBg;

  const resultBoxY = doc.y;
  doc.roundedRect(50, resultBoxY, pageWidth, 50, 6).fill(resultBg);

  doc
    .font('Helvetica-Bold')
    .fontSize(18)
    .fillColor(resultColor)
    .text(resultText, 50, resultBoxY + 14, { width: pageWidth, align: 'center' });

  doc.y = resultBoxY + 65;

  // Confidence score
  if (report.qualityAssessment?.confidence != null) {
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.textLight)
      .text(`Confidence: ${Math.round(report.qualityAssessment.confidence * 100)}%`, 50, doc.y, { width: pageWidth, align: 'center' });
    doc.moveDown(0.5);
  }

  // --- Error Summary ---
  checkPageBreak(doc, 140);
  drawSectionHeader(doc, 'Error Summary', pageWidth);

  const totalErrors = report.errorCount || 0;
  const timeSaved = report.timeSaved || 0;

  doc
    .font('Helvetica')
    .fontSize(11)
    .fillColor(COLORS.text)
    .text(`Total errors found: `, 50, doc.y, { continued: true })
    .font('Helvetica-Bold')
    .text(`${totalErrors}`)
    .font('Helvetica')
    .text(`Estimated time saved: `, 50, doc.y, { continued: true })
    .font('Helvetica-Bold')
    .text(`${timeSaved} minutes`);

  doc.moveDown(0.8);

  // Error breakdown boxes
  if (report.errorSummary) {
    const categories = [
      { key: 'placeholder', label: 'Placeholder', color: COLORS.placeholder },
      { key: 'consistency', label: 'Consistency', color: COLORS.consistency },
      { key: 'compliance', label: 'Compliance', color: COLORS.compliance },
      { key: 'formatting', label: 'Formatting', color: COLORS.formatting },
      { key: 'missing_data', label: 'Missing Data', color: COLORS.missing_data },
    ];

    const boxWidth = (pageWidth - 40) / 5;
    const boxY = doc.y;

    categories.forEach((cat, i) => {
      const x = 50 + i * (boxWidth + 10);
      const count = report.errorSummary[cat.key] || 0;

      doc.roundedRect(x, boxY, boxWidth, 50, 4).fill('#f9fafb');
      doc.roundedRect(x, boxY, boxWidth, 4, 2).fill(cat.color);

      doc
        .font('Helvetica-Bold')
        .fontSize(16)
        .fillColor(cat.color)
        .text(String(count), x, boxY + 12, { width: boxWidth, align: 'center' });

      doc
        .font('Helvetica')
        .fontSize(7)
        .fillColor(COLORS.textLight)
        .text(cat.label, x, boxY + 34, { width: boxWidth, align: 'center' });
    });

    doc.y = boxY + 65;
  }

  // --- Detailed Errors ---
  if (report.errors && report.errors.length > 0) {
    checkPageBreak(doc, 80);
    drawSectionHeader(doc, 'Detailed Error Analysis', pageWidth);

    // Group errors by type
    const grouped = {};
    report.errors.forEach((err) => {
      const key = err.type || 'other';
      if (!grouped[key]) grouped[key] = [];
      grouped[key].push(err);
    });

    const typeOrder = ['placeholder', 'consistency', 'compliance', 'formatting', 'missing_data', 'other'];

    typeOrder.forEach((type) => {
      if (!grouped[type]) return;
      const errors = grouped[type];
      const typeLabel = ERROR_TYPE_LABELS[type] || 'Other';
      const typeColor = COLORS[type] || COLORS.textLight;

      checkPageBreak(doc, 60);

      // Type header
      const headerY = doc.y;
      doc.roundedRect(50, headerY, pageWidth, 28, 4).fill(typeColor);
      doc
        .font('Helvetica-Bold')
        .fontSize(11)
        .fillColor(COLORS.white)
        .text(`${typeLabel} (${errors.length} ${errors.length === 1 ? 'error' : 'errors'})`, 62, headerY + 8, { width: pageWidth - 24 });

      doc.y = headerY + 36;

      // Individual errors
      errors.forEach((err, idx) => {
        checkPageBreak(doc, 80);

        const errY = doc.y;
        const severity = SEVERITY_LABELS[err.severity] || 'Medium';

        // Error number and severity
        doc
          .font('Helvetica-Bold')
          .fontSize(10)
          .fillColor(COLORS.text)
          .text(`Error ${idx + 1}`, 58, errY, { continued: true })
          .font('Helvetica')
          .fontSize(9)
          .fillColor(COLORS.textLight)
          .text(`  •  Severity: ${severity}`);

        doc.moveDown(0.3);

        // Error message
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor(COLORS.text)
          .text(err.message, 58, doc.y, { width: pageWidth - 16 });

        // Location
        if (err.location?.section || err.location?.page) {
          doc.moveDown(0.3);
          let locationText = 'Found in: ';
          if (err.location.section) locationText += err.location.section;
          if (err.location.page) locationText += ` (Page ${err.location.page})`;
          if (err.location.lineStart) {
            locationText += `, Line ${err.location.lineStart}`;
            if (err.location.lineEnd && err.location.lineEnd !== err.location.lineStart) {
              locationText += `-${err.location.lineEnd}`;
            }
          }

          doc
            .font('Helvetica-Oblique')
            .fontSize(9)
            .fillColor(COLORS.textLight)
            .text(locationText, 58, doc.y, { width: pageWidth - 16 });
        }

        // Original text snippet
        if (err.originalText) {
          doc.moveDown(0.3);
          const snippetY = doc.y;
          const snippetText = err.originalText.length > 200
            ? err.originalText.substring(0, 200) + '...'
            : err.originalText;

          doc.roundedRect(58, snippetY, pageWidth - 16, 4 + doc.heightOfString(snippetText, { width: pageWidth - 40, fontSize: 9 }) + 12, 3).fill('#fef3c7');

          doc
            .font('Helvetica')
            .fontSize(9)
            .fillColor('#92400e')
            .text(snippetText, 66, snippetY + 6, { width: pageWidth - 40 });

          doc.y += 6;
        }

        // Suggestion
        if (err.suggestion) {
          doc.moveDown(0.3);
          doc
            .font('Helvetica-Bold')
            .fontSize(9)
            .fillColor(COLORS.success)
            .text('Suggestion: ', 58, doc.y, { continued: true })
            .font('Helvetica')
            .fillColor(COLORS.text)
            .text(err.suggestion, { width: pageWidth - 80 });
        }

        doc.moveDown(0.6);

        // Separator between errors
        if (idx < errors.length - 1) {
          doc
            .moveTo(58, doc.y)
            .lineTo(50 + pageWidth - 8, doc.y)
            .strokeColor(COLORS.border)
            .lineWidth(0.5)
            .stroke();
          doc.moveDown(0.6);
        }
      });

      doc.moveDown(0.8);
    });
  } else if (report.status === 'analyzed') {
    checkPageBreak(doc, 60);
    drawSectionHeader(doc, 'Detailed Error Analysis', pageWidth);

    const noErrY = doc.y;
    doc.roundedRect(50, noErrY, pageWidth, 40, 6).fill(COLORS.successBg);
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor(COLORS.success)
      .text('No errors detected — document passed all checks.', 50, noErrY + 12, { width: pageWidth, align: 'center' });
    doc.y = noErrY + 55;
  }

  // --- Document Metadata ---
  if (report.metadata?.headerFields) {
    const hf = report.metadata.headerFields;
    const hasFields = hf.visitDate || hf.referenceNumber || hf.consultant;

    if (hasFields) {
      checkPageBreak(doc, 80);
      drawSectionHeader(doc, 'Document Metadata', pageWidth);

      const metaRows = [];
      if (hf.visitDate) metaRows.push(['Visit Date', hf.visitDate]);
      if (hf.referenceNumber) metaRows.push(['Reference Number', hf.referenceNumber]);
      if (hf.consultant) metaRows.push(['Consultant', hf.consultant]);

      drawInfoTable(doc, metaRows, pageWidth);
    }
  }

  // --- Footer on every page ---
  const pages = doc.bufferedPageRange();
  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(COLORS.textLight)
      .text(
        `QC Checker — Analysis Report  |  Page ${i + 1} of ${pages.count}`,
        50,
        doc.page.height - 35,
        { width: pageWidth, align: 'center' }
      );
  }

  return doc;
};

function drawSectionHeader(doc, title, pageWidth) {
  doc.moveDown(0.5);
  doc
    .font('Helvetica-Bold')
    .fontSize(14)
    .fillColor(COLORS.primary)
    .text(title, 50, doc.y, { width: pageWidth });

  doc
    .moveTo(50, doc.y + 2)
    .lineTo(50 + pageWidth, doc.y + 2)
    .strokeColor(COLORS.primary)
    .lineWidth(1.5)
    .stroke();

  doc.moveDown(0.6);
}

function drawInfoTable(doc, rows, pageWidth) {
  const labelWidth = 150;

  rows.forEach(([label, value]) => {
    const rowY = doc.y;

    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.textLight)
      .text(label, 58, rowY, { width: labelWidth });

    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(value || 'N/A', 58 + labelWidth, rowY, { width: pageWidth - labelWidth - 16 });

    doc.y = rowY + 18;
  });

  doc.moveDown(0.3);
}

function checkPageBreak(doc, requiredSpace) {
  const bottomMargin = doc.page.margins.bottom;
  const pageBottom = doc.page.height - bottomMargin;

  if (doc.y + requiredSpace > pageBottom) {
    doc.addPage();
  }
}

module.exports = { generateReportPdf };
