image: node:18

default:
  
  tags:
    - comsc-ci

stages:
  - install
  - build
  - test

cache:
  key: node-cache-key
  paths:
    - backend/node_modules/
    - frontend/node_modules/

install-backend:
  stage: install
  script:
    - cd backend && npm install
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1 week

install-frontend:
  stage: install
  script:
    - cd frontend && npm install
  artifacts:
    paths:
      - frontend/node_modules/
    expire_in: 1 week

build-frontend:
  stage: build
  dependencies:
    - install-frontend
  script:
    - cd frontend && npm run build

test-backend:
  stage: test
  dependencies:
    - install-backend
  script:
    - cd backend && npm test  --passWithNoTests #passes with no test for now
