const checklistConfig = {
  version: 'BAFE-SP205-Appendix-D-2022-v1',
  items: [
    {
      id: '1A',
      title: 'Identity of the client',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [
        /\bclient\s*:\s*[A-Z][a-zA-Z\s&.,'-]{3,}/i,
        /\bon behalf of\s+[A-Z][a-zA-Z\s&.,'-]{3,}/i,
        /\bfor and on behalf of\s+[A-Z][a-zA-Z\s&.,'-]{3,}/i,
        /\bprepared for\s*:\s*[A-Z][a-zA-Z\s&.,'-]{3,}/i,
      ],
      suggestion: 'State the client identity in the report header/introduction.',
    },
    {
      id: '1B',
      title: 'Identity of responsible person / duty holder',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [
        /\bresponsible person\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
        /\bduty holder\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
        /\bresponsible person\b.{0,100}\b[A-Z][a-z]+\s+[A-Z][a-z]+/i,
      ],
      suggestion: 'Identify the responsible person or duty holder.',
    },
    {
      id: '1C',
      title: 'Person responsible for fire safety at premises',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [
        /\bresponsib(le|ility).{0,40}fire safety\b.{0,50}[A-Z][a-z]+/i,
        /\bfire safety manager\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
        /\bfire safety officer\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
      ],
      suggestion: 'Identify who holds fire safety responsibility at the premises.',
    },
    {
      id: '1D',
      title: 'Competent person appointed by responsible person',
      severity: 'medium',
      sectionHint: '2. Competent Persons',
      mode: 'any',
      patterns: [
        /\bcompetent person\b.{0,50}[A-Z][a-z]+\s+[A-Z][a-z]+/i,
        /\bassessor\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
        /\bconsultant\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
      ],
      suggestion: 'Identify the competent person appointed to assist with fire precautions.',
    },
    {
      id: '1E',
      title: 'Exact location and extent of assessed premises',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [
        /\b(site address|location of premises|address)\s*:\s*[A-Z0-9][a-zA-Z0-9\s,.-]{10,}/i,
        /\b(extent|areas covered|scope of assessment|assessment covers)\b/i,
      ],
      suggestion: 'State both location and extent/scope of the assessment.',
    },
    {
      id: '1F',
      title: 'Assessment date(s)',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [
        /\b(visit date|assessment date)\s*:\s*\d{1,2}(st|nd|rd|th)?\s+\w+\s+\d{4}/i,
        /\bdate(s)? of assessment\s*:\s*\d{1,2}/i,
        /\bvisit date\s*:\s*\S{5,}/i,
      ],
      suggestion: 'Include clear date(s) on which the FRA was carried out.',
    },
    {
      id: '1G',
      title: 'Key individuals consulted and their roles',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [
        /\b(information obtained|consulted)\s+(from|with)\s+[A-Z][a-z]+/i,
        /\b(accompanied by|on.?site contact)\s*:\s*[A-Z][a-zA-Z\s.,'-]{3,}/i,
        /[A-Z][a-z]+\s+[A-Z][a-z]+\s*[-–]\s*(Director|Manager|Officer|Consultant|Assessor)/i,
      ],
      suggestion: 'List key people consulted and their role in the assessment.',
    },
    {
      id: '1H',
      title: 'Review criteria and recommended review date',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'all',
      patterns: [
        /\b(review date|next review|recommended review)\s*:\s*\S{5,}/i,
        /\b(review criteria|triggers? for review|significant change)\b/i,
      ],
      suggestion: 'Provide review criteria and a recommended review date.',
    },
    {
      id: '1I',
      title: 'Significant findings',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [
        /\bsignificant findings?\b.{0,200}\b(identified|found|noted|observed)/i,
        /\b(key findings?|main findings?|principal findings?)\b/i,
      ],
      suggestion: 'Document significant findings from the assessment.',
    },
    {
      id: '1J',
      title: 'Overall assessment of risk',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [
        /\b(overall (assessment )?of risk|overall risk level|risk to life)\s*:\s*\S{3,}/i,
        /\b(trivial|tolerable|moderate|substantial|intolerable)\s+risk\b/i,
      ],
      suggestion: 'Include an explicit overall risk assessment.',
    },
    {
      id: '1K',
      title: 'Information required by relevant legislation',
      severity: 'medium',
      sectionHint: '4. Terms and Definitions',
      mode: 'any',
      patterns: [
        /\bregulatory reform.{0,20}fire safety.{0,20}order\b/i,
        /\bfire safety order 2005\b/i,
        /\brelevant legislation\b.{0,100}\b(complian|require|reference)/i,
      ],
      suggestion: 'Reference and document information required by relevant legislation.',
    },
    {
      id: '1L',
      title: 'Action list with severity, urgency and timescales',
      severity: 'high',
      sectionHint: '9. Risk Assessment and Action Plan',
      mode: 'all',
      patterns: [
        /\b(action plan|actions arising|recommendations?)\b/i,
        /\b(severity|priority|urgency)\s*:\s*\S{3,}/i,
        /\b(timescale|target date|completion date|deadline)\s*:\s*\S{3,}/i,
      ],
      suggestion: 'Provide actions with severity/priority and completion timescales.',
    },
    {
      id: '1M',
      title: 'Unique reference identifier',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [
        /\breference\s*(number|no\.?)?\s*:\s*[A-Z0-9/-]{4,}/i,
        /\bunique reference\s*:\s*\S{4,}/i,
        /\breport\s*(number|no\.?|ref)\s*:\s*[A-Z0-9/-]{4,}/i,
      ],
      suggestion: 'Include a unique reference identifier.',
    },

    {
      id: '2A',
      title: 'Premises/building/process description',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [
        /\b(description of (the )?premises|premises description|building description)\b/i,
        /\b(process(es)?|activities|operations?|undertaking)\s+(carried out|on site|at the premises)\b/i,
      ],
      suggestion: 'Describe premises, building and processes carried out on site.',
    },
    {
      id: '2B',
      title: 'Size/storeys/staircases/lift shafts/construction/use/evacuation policy',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [
        /\b(gross internal area|floor area|sq ft|square (feet|metres)|size of premises)\b/i,
        /\b(number of )?(storeys?|floors?)\s*:\s*\d+/i,
      ],
      suggestion: 'Include building size and structural/use/evacuation details.',
    },
    {
      id: '2C',
      title: 'Occupant information and persons especially at risk',
      severity: 'high',
      sectionHint: '5.14. Persons at Risk',
      mode: 'all',
      patterns: [
        /\b(occupants?|persons?\s+at\s+risk|especially at risk)\b/i,
        /\b(disabilit|mobility|sensory|cognitive).{0,30}(impair|need|require|assist)/i,
      ],
      suggestion: 'Document occupants, especially at-risk persons, disability/public-use details and occupancy.',
    },
    {
      id: '2D',
      title: 'Care home staff/resident ratio and non-ambulant residents (if applicable)',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      appliesWhenAny: [
        /\b(residential care home|nursing home|care home|assisted living|extra care housing)\b/i,
        /\b(CQC|care quality commission|residents?\s+in\s+care|care provider)\b/i,
      ],
      notAppliesWhen: /\b(for (residential )?care homes?\s+(identify|include|record)|care home staff\/resident ratio|if applicable|not applicable|n\/a|not a care home|no residential care|care home\s*:\s*no)\b/i,
      patterns: [
        /\b(day shift|night shift)\s*:\s*\d+/i,
        /\bstaff\s*\/?\s*residents?\s*ratio\b/i,
        /\bnon-ambulant\b/i,
      ],
      suggestion: 'For care homes, include staff/resident ratios and non-ambulant resident details.',
    },
    {
      id: '2E',
      title: 'Previous fires and likely causes',
      severity: 'medium',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [
        /\b(previous fire|history of fire|fire history)\b.{0,100}\b(yes|no|none|recorded|occurred)/i,
        /\bfire cause\b.{0,50}\b(arson|electrical|smoking|cooking|hot works?)/i,
      ],
      suggestion: 'Record previous fire history and likely causes where known.',
    },
    {
      id: '2F',
      title: 'Overall premises risk rating with likelihood/consequence',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'all',
      patterns: [
        /\b(risk rating|overall premises risk|overall risk)\s*:\s*(trivial|tolerable|moderate|substantial|intolerable)/i,
        /\b(likelihood|probability)\s*:\s*(very low|low|medium|high|very high)/i,
      ],
      suggestion: 'Record overall premises risk rating with likelihood and consequence.',
    },
    {
      id: '2G',
      title: 'Detection/warning systems and alarm category details',
      severity: 'high',
      sectionHint: '9.6. Fire Protection Systems - Fire Alarm',
      mode: 'all',
      notAppliesWhen: /\b(no (automatic )?fire alarm (system )?(installed|present)|fire alarm\s*:\s*(none|n\/a)|alarm category\s*:\s*(none|n\/a)|not applicable)\b/i,
      patterns: [
        /\b(fire (detection|alarm) system|automatic fire detection|AFD)\b/i,
        /\bbs\s*5839\b/i,
        /\bcategory\s*:\s*(L[1-5]|P[1-2]|M)/i,
      ],
      suggestion: 'Describe fire detection/warning system and BS 5839 category/coverage details.',
    },
    {
      id: '2H',
      title: 'Means of escape details',
      severity: 'high',
      sectionHint: 'Means of Escape',
      mode: 'any',
      patterns: [
        /\bmeans of escape\b.{0,100}\b(adequate|satisfactory|provided|route)/i,
        /\b(final exit|escape route|travel distance)\s*:\s*\S{3,}/i,
      ],
      suggestion: 'Describe means of escape, final exits, and travel distance/exit-width details where relevant.',
    },
    {
      id: '2I',
      title: 'Compartmentation and fire doors',
      severity: 'high',
      sectionHint: '9.7. Compartmentation',
      mode: 'all',
      patterns: [
        /\bcompartmentation\b.{0,100}\b(adequate|satisfactory|maintained|breached)/i,
        /\bfire doors?\b.{0,50}\b(condition|inspection|FD\d{2}|satisfactory)/i,
      ],
      suggestion: 'Include compartmentation details and fire door condition/inspection status.',
    },
    {
      id: '2J',
      title: 'Emergency lighting type and coverage',
      severity: 'high',
      sectionHint: 'Emergency Lighting',
      mode: 'all',
      notAppliesWhen: /\b(emergency lighting\s*:\s*(none|n\/a|not applicable)|no emergency lighting (installed|provided)|not required due to borrowed light)\b/i,
      patterns: [
        /\bemergency lighting\b.{0,50}\b(type|maintained|non-maintained|provided)/i,
        /\bemergency lighting\s*:\s*(yes|provided|installed|maintained|non-maintained)/i,
      ],
      suggestion: 'State emergency lighting type and where it is provided/observed.',
    },
  ],
};

module.exports = checklistConfig;
