const checklistConfig = {
  version: 'BAFE-SP205-Appendix-D-2022-v1',
  items: [
    // Section 1 (A-M)
    {
      id: '1A',
      title: 'Identity of the client',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [/\b(client|on behalf of|for and on behalf of)\b/i],
      suggestion: 'State the client identity in the report header/introduction.',
    },
    {
      id: '1B',
      title: 'Identity of responsible person / duty holder',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [/\b(responsible person|duty holder)\b/i],
      suggestion: 'Identify the responsible person or duty holder.',
    },
    {
      id: '1C',
      title: 'Person responsible for fire safety at premises',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [/\b(responsib(le|ility).{0,40}fire safety|fire safety manager)\b/i],
      suggestion: 'Identify who holds fire safety responsibility at the premises.',
    },
    {
      id: '1D',
      title: 'Competent person appointed by responsible person',
      severity: 'medium',
      sectionHint: '2. Competent Persons',
      mode: 'any',
      patterns: [/\b(competent person|assessor|consultant)\b/i],
      suggestion: 'Identify the competent person appointed to assist with fire precautions.',
    },
    {
      id: '1E',
      title: 'Exact location and extent of assessed premises',
      severity: 'high',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [/\b(site address|location of premises)\b/i, /\b(extent|areas covered|scope)\b/i],
      suggestion: 'State both location and extent/scope of the assessment.',
    },
    {
      id: '1F',
      title: 'Assessment date(s)',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [/\b(visit date|assessment date|date(s)? of assessment)\b/i],
      suggestion: 'Include clear date(s) on which the FRA was carried out.',
    },
    {
      id: '1G',
      title: 'Key individuals consulted and their roles',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'any',
      patterns: [
        /\b(key individuals?|information obtained|consulted)\b/i,
        /\b(accompanied|available|on.?site contact).{0,60}(director|manager|officer)\b/i,
        /[A-Z][a-z]+\s+[A-Z][a-z]+\s*[-–]\s*(Director|Manager|Officer|Consultant|Assessor)/i,
      ],
      suggestion: 'List key people consulted and their role in the assessment.',
    },
    {
      id: '1H',
      title: 'Review criteria and recommended review date',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'all',
      patterns: [/\b(review date|review)\b/i, /\b(criteria|trigger|recommended)\b/i],
      suggestion: 'Provide review criteria and a recommended review date.',
    },
    {
      id: '1I',
      title: 'Significant findings',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [/\b(significant findings?|findings)\b/i],
      suggestion: 'Document significant findings from the assessment.',
    },
    {
      id: '1J',
      title: 'Overall assessment of risk',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [/\b(overall (assessment )?of risk|risk level|risk to life)\b/i],
      suggestion: 'Include an explicit overall risk assessment.',
    },
    {
      id: '1K',
      title: 'Information required by relevant legislation',
      severity: 'medium',
      sectionHint: '4. Terms and Definitions',
      mode: 'any',
      patterns: [/\b(relevant legislation|regulatory reform|fire safety order|legislation)\b/i],
      suggestion: 'Reference and document information required by relevant legislation.',
    },
    {
      id: '1L',
      title: 'Action list with severity, urgency and timescales',
      severity: 'high',
      sectionHint: '9. Risk Assessment and Action Plan',
      mode: 'all',
      patterns: [/\b(action plan|actions arising|recommendations)\b/i, /\b(severity|priority|urgency)\b/i, /\b(timescale|target date|completion date)\b/i],
      suggestion: 'Provide actions with severity/priority and completion timescales.',
    },
    {
      id: '1M',
      title: 'Unique reference identifier',
      severity: 'high',
      sectionHint: 'Header',
      mode: 'any',
      patterns: [/\b(reference number|unique reference|ref(erence)?\b)\b/i],
      suggestion: 'Include a unique reference identifier.',
    },

    // Section 2 (A-J)
    {
      id: '2A',
      title: 'Premises/building/process description',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [/\b(description of (the )?premises|description of undertakings|usage)\b/i, /\b(process(es)?|activities)\b/i],
      suggestion: 'Describe premises, building and processes carried out on site.',
    },
    {
      id: '2B',
      title: 'Size/storeys/staircases/lift shafts/construction/use/evacuation policy',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      patterns: [/\b(size|sq ft|square (feet|metres)|storeys|staircases?|lift shafts?)\b/i, /\b(construction|building classification|usage|evacuation policy)\b/i],
      suggestion: 'Include building size and structural/use/evacuation details.',
    },
    {
      id: '2C',
      title: 'Occupant information and persons especially at risk',
      severity: 'high',
      sectionHint: '5.14. Persons at Risk',
      mode: 'all',
      patterns: [/\b(occupants?|persons at risk|especially at risk)\b/i, /\b(disabilit|general public|occupancy)\b/i],
      suggestion: 'Document occupants, especially at-risk persons, disability/public-use details and occupancy.',
    },
    {
      id: '2D',
      title: 'Care home staff/resident ratio and non-ambulant residents (if applicable)',
      severity: 'medium',
      sectionHint: '5. Premises Details',
      mode: 'all',
      // Only apply when there is a real care-setting signal, not just template wording.
      appliesWhenAny: [
        /\b(residential care home|nursing home|care home|assisted living|extra care housing)\b/i,
        /\b(CQC|care quality commission|residents?\s+in\s+care|care provider)\b/i,
      ],
      // Ignore checklist/template instructions and explicit non-applicability statements.
      notAppliesWhen: /\b(for (residential )?care homes?\s+(identify|include|record)|care home staff\/resident ratio|if applicable|not applicable|n\/a|not a care home|no residential care|care home\s*:\s*no)\b/i,
      patterns: [/\b(day shift|night shift|staff\/residents? ratio)\b/i, /\b(non-ambulant|storey location)\b/i],
      suggestion: 'For care homes, include staff/resident ratios and non-ambulant resident details.',
    },
    {
      id: '2E',
      title: 'Previous fires and likely causes',
      severity: 'medium',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'any',
      patterns: [/\b(previous fire|history of fire|arson|electrical faults?|smoking|portable heaters?|cooking|hot works?)\b/i],
      suggestion: 'Record previous fire history and likely causes where known.',
    },
    {
      id: '2F',
      title: 'Overall premises risk rating with likelihood/consequence',
      severity: 'high',
      sectionHint: '8. Fire Risk Assessment',
      mode: 'all',
      patterns: [/\b(risk rating|overall premises risk)\b/i, /\b(likelihood|consequence)\b/i],
      suggestion: 'Record overall premises risk rating with likelihood and consequence.',
    },
    {
      id: '2G',
      title: 'Detection/warning systems and alarm category details',
      severity: 'high',
      sectionHint: '9.6. Fire Protection Systems - Fire Alarm',
      mode: 'all',
      // Some premises explicitly have no alarm system/category to classify.
      notAppliesWhen: /\b(no (automatic )?fire alarm (system )?(installed|present)|fire alarm\s*:\s*(none|n\/a)|alarm category\s*:\s*(none|n\/a)|not applicable)\b/i,
      patterns: [/\b(means for detecting fire|fire alarm|warning to occupants)\b/i, /\b(bs\s*5839|category|L[1-5]|P[1-2])\b/i],
      suggestion: 'Describe fire detection/warning system and BS 5839 category/coverage details.',
    },
    {
      id: '2H',
      title: 'Means of escape details',
      severity: 'high',
      sectionHint: 'Means of Escape',
      mode: 'any',
      patterns: [/\b(means of escape|final exits?|travel distances?|exit width|stair wells?)\b/i],
      suggestion: 'Describe means of escape, final exits, and travel distance/exit-width details where relevant.',
    },
    {
      id: '2I',
      title: 'Compartmentation and fire doors',
      severity: 'high',
      sectionHint: '9.7. Compartmentation',
      mode: 'all',
      patterns: [/\b(compartmentation|fire rating)\b/i, /\b(fire doors?|door inspections?)\b/i],
      suggestion: 'Include compartmentation details and fire door condition/inspection status.',
    },
    {
      id: '2J',
      title: 'Emergency lighting type and coverage',
      severity: 'high',
      sectionHint: 'Emergency Lighting',
      mode: 'all',
      // Allow explicit N/A statements for premises where emergency lighting is not required/provided.
      notAppliesWhen: /\b(emergency lighting\s*:\s*(none|n\/a|not applicable)|no emergency lighting (installed|provided)|not required due to borrowed light)\b/i,
      patterns: [/\b(emergency lighting)\b/i, /\b(maintained|non-maintained|means of escape|locations observed)\b/i],
      suggestion: 'State emergency lighting type and where it is provided/observed.',
    },
  ],
};

module.exports = checklistConfig;
